### ISSUE TITLE
InteractionResponse.send_message で View.build が使えない

### ISSUE THREAD

**Issue by Lapis256** [sizumita/discord-ext-ui#16]
on_interaction内で使おうとしたらエラーが発生しました。

```py
class Bot(commands.Bot):
    async def on_interaction(self, interaction):
        if interaction.type != discord.InteractionType.application_command:
            return

        view = await SampleView(self).setup()
        await interaction.response.send_message(**view.build())
```
```
Ignoring exception in on_interaction
Traceback (most recent call last):
  File "/home/lapis/mcbe-bot/.venv/lib/python3.9/site-packages/discord/client.py", line 331, in _run_event
    await coro(*args, **kwargs)
  File "/home/lapis/mcbe-bot/bot.py", line 86, in on_interaction
    await interaction.response.send_message(**view.build())
  File "/home/lapis/mcbe-bot/.venv/lib/python3.9/site-packages/discord/interactions.py", line 494, in send_message
    payload['embeds'] = [e.to_dict() for e in embeds]
  File "/home/lapis/mcbe-bot/.venv/lib/python3.9/site-packages/discord/interactions.py", line 494, in <listcomp>
    payload['embeds'] = [e.to_dict() for e in embeds]
AttributeError: 'NoneType' object has no attribute 'to_dict'
```

**Comment by sizumita** [comment]
`await interaction.response.send_message(**view.build())`　を
`await view.start(interaction)`
に変更したらどうなります？

**Comment by Lapis256** [comment]
問題なく動作しました

**Comment by sizumita** [comment]
View.buildはうまく動かない気がするのでそちらを使ってもらえれば...ちょっと原因探してみます
